name: Rust

on:
  push:
    branches: [ master ]
    paths:
      - carage
  pull_request:
    branches: [ master ]
    paths:
      - carage

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ./carage
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./carage     
    - name: Run tests
      run: cargo fmt -- --check
      working-directory: ./carage     
    - name: Run tests
      run: cargo clippy -- --Dwarnings
      working-directory: ./carage     
